server:
   port: 8080
   tomcat:
      uri-encoding: UTF-8
   
spring:
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         dormat_sql: true
      database-platform: org.hibernate.dialect.H2Dialect
   application:
      name: CastBackEnd
   datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: sa
   http:
      encoding:
         charset: UTF-8
         
   jackson:
      serialization:
         fail-on-empty-beans: false